import { app } from "electron";
import { promises as fs } from "node:fs";
import { dirname, join } from "node:path";
import type { IntegrationSyncData } from "@elevator/shared";

/**
 * Per-instance JSON cache for sync payloads and OAuth token sets. Stored
 * under `userData/integration-cache/<instanceId>.json` so it deletes cleanly
 * with the instance (registry calls `clearCache` from `deleteInstance`).
 *
 * The cache contains only non-secret integration data (events, headers,
 * report rows). Refresh tokens are written here intentionally because
 * `safeStorage` cannot keep them encrypted-at-rest reliably for headless
 * background refresh; users who need stricter handling can disable sync.
 */

interface CacheFile {
  sync?: IntegrationSyncData;
  oauth?: {
    accessToken: string;
    refreshToken?: string;
    expiresAt: string;
    scope?: string;
    tokenType?: string;
  };
  extras?: Record<string, unknown>;
}

function cacheDir(): string {
  return join(app.getPath("userData"), "integration-cache");
}

function cachePath(instanceId: string): string {
  // instanceId is a uuid generated by us — no path-traversal vector — but
  // assert anyway in case a caller plumbs untrusted input later.
  if (!/^[A-Za-z0-9_-]+$/.test(instanceId)) {
    throw new Error(`Invalid instance id for cache: ${instanceId}`);
  }
  return join(cacheDir(), `${instanceId}.json`);
}

async function readFile(instanceId: string): Promise<CacheFile> {
  try {
    const raw = await fs.readFile(cachePath(instanceId), "utf8");
    return JSON.parse(raw) as CacheFile;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === "ENOENT") return {};
    throw err;
  }
}

async function writeFile(instanceId: string, data: CacheFile): Promise<void> {
  const path = cachePath(instanceId);
  await fs.mkdir(dirname(path), { recursive: true });
  await fs.writeFile(path, JSON.stringify(data, null, 2), { mode: 0o600 });
}

export async function getSyncCache(
  instanceId: string
): Promise<IntegrationSyncData | null> {
  const file = await readFile(instanceId);
  return file.sync ?? null;
}

export async function setSyncCache(
  instanceId: string,
  data: IntegrationSyncData
): Promise<void> {
  const file = await readFile(instanceId);
  file.sync = data;
  await writeFile(instanceId, file);
}

export async function getOAuthTokens(
  instanceId: string
): Promise<CacheFile["oauth"] | null> {
  const file = await readFile(instanceId);
  return file.oauth ?? null;
}

export async function setOAuthTokens(
  instanceId: string,
  tokens: CacheFile["oauth"]
): Promise<void> {
  const file = await readFile(instanceId);
  file.oauth = tokens;
  await writeFile(instanceId, file);
}

export async function clearCache(instanceId: string): Promise<void> {
  try {
    await fs.unlink(cachePath(instanceId));
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
}
